- name: zsh for root user
  file:
    path: "{{ item.home | d('/home' + item.username) }}/.zshrc"
    state: present
  become: yes

- name: Include zsh config for users
  lineinfile:
    path: "{{ item.home | d('/home' + item.username) }}/.zshrc"
    line: "source /usr/share/zsh-config/.zshrc"

